### PR TITLE
Fixes #25 Fix CustomMatcher.describeMismatch does not properly descri…

### LINKED ISSUE #25: CustomMatcher.describeMismatch can fail if featureValueOf throws
From dart-lang/test#257 (originally from dart-lang/sdk#20398).

---

**What steps will reproduce the problem?**
1. Write code like:
class BadCustomMatcher extends CustomMatcher
{
&nbsp;&nbsp;BadCustomMatcher(): super(&quot;feature&quot;, &quot;description&quot;, {1: &quot;a&quot;});

&nbsp;&nbsp;featureValueOf(actual) =&gt; throw new Exception(&quot;bang&quot;);
}

main () {
&nbsp;&nbsp;test(&quot;test&quot;, () {
&nbsp;&nbsp;&nbsp;&nbsp;expect(&quot;a&quot;, new BadCustomMatcher());
&nbsp;&nbsp;});
}
2. run it
3. Get a traceback like:
ERROR: test
&nbsp;&nbsp;Test failed: Caught The null object does not have a method '[]'.
&nbsp;&nbsp;
&nbsp;&nbsp;NoSuchMethodError: method not found: '[]'
&nbsp;&nbsp;Receiver: null
&nbsp;&nbsp;Arguments: [&quot;reason&quot;]
&nbsp;&nbsp;dart:core-patch/object_patch.dart 45           Object.noSuchMethod
&nbsp;&nbsp;package:matcher/src/core_matchers.dart 263:28  _DeepMatcher.describeMismatch
&nbsp;&nbsp;package:matcher/src/core_matchers.dart 740:30  CustomMatcher.describeMismatch
&nbsp;&nbsp;package:matcher/src/expect.dart 146:27         _defaultErrorFormatter
&nbsp;&nbsp;package:matcher/src/expect.dart 113:31         DefaultFailureHandler.failMatch
&nbsp;&nbsp;package:matcher/src/expect.dart 73:29          expect
&nbsp;&nbsp;test.dart 129:11                      main.&lt;fn&gt;

**What is the expected output? What do you see instead?**
I'd expect to get a description of the exception. Indeed looking at the code I think I would if the inner matcher didn't use the matchState in it's own describeMismatch

**What version of the product are you using?**

**On what operating system?**

**What browser (if applicable)?**

**Please provide any additional information below.**

### PR DESCRIPTION
**Pull request by kunzhao77**
…be exception

@nex3 
Please review.

### CODE REVIEW

**Comment by kevmoo** [comment]
No tests?

**Comment by kunzhao77** [comment]
@kevmoo @nex3 
Test added.

File: lib/src/core_matchers.dart [hunk 1]
```diff
@@ -614,9 +614,13 @@ class CustomMatcher extends Matcher {
   featureValueOf(actual) => actual;
 
   bool matches(item, Map matchState) {
-    var f = featureValueOf(item);
-    if (_matcher.matches(f, matchState)) return true;
-    addStateInfo(matchState, {'feature': f});
+    try {
+      var f = featureValueOf(item);
+      if (_matcher.matches(f, matchState)) return true;
+      addStateInfo(matchState, {'feature': f});
```
Comment (nex3) [inline lib/src/core_matchers.dart]: Since `matchState` has a global namespace, it's probably a good idea to prefix these keys with the matcher name—`custom.feature` and so on.

File: lib/src/core_matchers.dart [hunk 2]
```diff
@@ -625,14 +629,24 @@ class CustomMatcher extends Matcher {
 
   Description describeMismatch(
       item, Description mismatchDescription, Map matchState, bool verbose) {
+    if (matchState['exception'] != null) {
+      mismatchDescription.add('threw ').addDescriptionOf(matchState['exception']);
+      if (verbose) {
```
Comment (nex3) [inline lib/src/core_matchers.dart]: I think we should always include the stack trace.

File: lib/src/core_matchers.dart [hunk 3]
```diff
@@ -625,14 +629,24 @@ class CustomMatcher extends Matcher {
...
+        mismatchDescription.add(' at ').add(matchState['stack'].toString());
```
Comment (nex3) [inline lib/src/core_matchers.dart]: Add a newline before the stack trace; "at" is probably not necessary.

To be maximally usable from within tests, this should include the [stack chain](https://github.com/dart-lang/stack_trace/#stack-chains). You'll have to add `stack_trace` as a dependency.

**Comment by kzhdev** [comment]
@nex3 

Pushed another commit to address your review comments. Please take a look again. Thanks.

File: lib/src/core_matchers.dart [hunk 4]
```diff
@@ -617,9 +617,9 @@ class CustomMatcher extends Matcher {
     try {
       var f = featureValueOf(item);
       if (_matcher.matches(f, matchState)) return true;
-      addStateInfo(matchState, {'feature': f});
+      addStateInfo(matchState, {'custom.feature': f});
     } catch (e, s) {
-      addStateInfo(matchState, {'exception': e, 'stack': s});
+      addStateInfo(matchState, {'custom.exception': e, 'stack': s});
```
Comment (nex3) [inline lib/src/core_matchers.dart]: `stack` needs to be namespaced as well.

**Comment by kunzhao77** [comment]
@nex3
Push another commit to add namespace to stack and include stack chain. Please take another look. Thanks.

File: lib/src/core_matchers.dart [hunk 5]
```diff
@@ -614,25 +615,47 @@ class CustomMatcher extends Matcher {
...
+        rt = true;
+        return;
+      }
+      addStateInfo(matchState, {'custom.feature': f});
+    }, onError: (error, stackChain) {
+      addStateInfo(matchState, {
+        'custom.exception': error.toString(),
+        'custom.stack': stackChain.toString()
+      });
+    });
```
Comment (nex3) [inline lib/src/core_matchers.dart]: `Chain.capture()` isn't necessary here, and it won't provide any extra information since it only captures information within the call. You can just use `new Chain.forTrace()` on the stack trace you already captured, and call `.terse.toString()` on it when you print it.

Comment (kunzhao77) [inline lib/src/core_matchers.dart]: @nex3 
Pushed another commit to address this comment.

**Comment by nex3** [comment]
Thanks for the patch!
